### ISSUE TITLE
Cool portfolio

### ISSUE THREAD

**Issue by guilyx** [pr2tik1/pr2tik1.github.io#1]
Care to add it here ? : https://github.com/guilyx/awesome-github-pages-portfolios
Trying to make people aware of how easy it is to host a portfolio on github by making a list :)

Thanks ;)

**Comment by pr2tik1** [comment]
Yes that's great! Please add, or shall I PR? @guilyx

**Comment by pr2tik1** [comment]
Thank you so much! Made a PR [#2](https://github.com/guilyx/awesome-github-pages-portfolios/pull/2#issue-475313496).
